services:
  - type: web
    name: hospitalease
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hospitalease-db
          property: connectionString

databases:
  - name: hospitalease-db
    plan: free
    databaseName: myhmsdb
